# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "aws-dynamodb-example"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0"
aws-sdk-dynamodb = "0"
tokio = { version = "1", features = ["full"] }
